// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"数据看板","path":"/dashboard","icon":"DashboardOutlined","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"种鹅档案","path":"/goose/list","icon":"TeamOutlined","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"鹅只详情","path":"/goose/detail/:id","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"产蛋箱管理","path":"/nestbox/list","icon":"HomeOutlined","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"产蛋箱详情","path":"/nestbox/detail/:id","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"6"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Goose__List__index" */'@/pages/Goose/List/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Goose__Detail__index" */'@/pages/Goose/Detail/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__NestBox__List__index" */'@/pages/NestBox/List/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__NestBox__Detail__index" */'@/pages/NestBox/Detail/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/yujian/Code/Web/goose-egg-laying-monitoring/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
