// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/yujian/Code/Web/goose-egg-laying-monitoring/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import TeamOutlined from '/Users/yujian/Code/Web/goose-egg-laying-monitoring/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import HomeOutlined from '/Users/yujian/Code/Web/goose-egg-laying-monitoring/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/HomeOutlined';
export default { DashboardOutlined, TeamOutlined, HomeOutlined };
